# ===============H2=================
spring:
  h2:
    console:
      enabled: true
      settings:
        trace: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
    schema: classpath:db/schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

---
